# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalendarApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 6.2.0'
  target 'CalendarApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'CalendarAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

